/**
 * Human Assessment Engine - Reusable Question Bank
 * Stage 1: Personality Assessment (50 Questions → 25 Marks)
 * Stage 2: Mindset Assessment (25 Questions → 20 Marks)
 * Stage 3: Decision Making Assessment (15 Questions → 15 Marks)
 * Stage 4: General Awareness Assessment (15 Questions → 15 Marks)
 * Stage 5: Aptitude Assessment (10 Questions → 10 Marks)
 * Stage 6: Communication & Learning Agility Assessment (15 Questions → 15 Marks)
 */

import { QuestionItem } from "@/types/assessmentEngine";

const likertOptions = [
  { id: "lik_1", text: "1 - Strongly Disagree", weight: 1 },
  { id: "lik_2", text: "2 - Disagree", weight: 2 },
  { id: "lik_3", text: "3 - Neutral", weight: 3 },
  { id: "lik_4", text: "4 - Agree", weight: 4 },
  { id: "lik_5", text: "5 - Strongly Agree", weight: 5 },
];

export const PERSONALITY_QUESTION_BANK: QuestionItem[] = [
  // ================= A. DISCIPLINE & RESPONSIBILITY (Q1-Q8: 4 Marks) =================
  {
    id: "q_disc_01",
    stage: "personality",
    domain: "Discipline & Responsibility",
    subDomain: "Morning Routine & Consistency",
    difficulty: "Easy",
    type: "frequency",
    questionText: "How often do you wake up at approximately the same time every day?",
    estimatedTimeSeconds: 15,
    marks: 0.5,
    options: [
      { id: "freq_1", text: "Never", weight: 1 },
      { id: "freq_2", text: "Rarely", weight: 2 },
      { id: "freq_3", text: "Sometimes", weight: 3 },
      { id: "freq_4", text: "Most Days", weight: 4 },
      { id: "freq_5", text: "Daily", weight: 5 },
    ],
    scoringRules: "Linear scale measuring sleep/wake routine consistency.",
    tags: ["Discipline", "Routine"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Consistency" },
  },
  {
    id: "q_disc_02",
    stage: "personality",
    domain: "Discipline & Responsibility",
    subDomain: "Schedule & Planning",
    difficulty: "Easy",
    type: "likert",
    questionText: "I maintain a structured daily routine or schedule.",
    estimatedTimeSeconds: 15,
    marks: 0.5,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Discipline", "Planning"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Discipline" },
  },
  {
    id: "q_disc_03",
    stage: "personality",
    domain: "Discipline & Responsibility",
    subDomain: "Deadline Integrity",
    difficulty: "Medium",
    type: "likert",
    questionText: "I complete important tasks well before the deadline without needing external reminders.",
    estimatedTimeSeconds: 15,
    marks: 0.5,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Responsibility", "Deadlines"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Responsibility" },
  },
  {
    id: "q_disc_04",
    stage: "personality",
    domain: "Discipline & Responsibility",
    subDomain: "Procrastination Control",
    difficulty: "Medium",
    type: "likert",
    questionText: "I avoid procrastinating on important responsibilities even when they are challenging or unappealing.",
    estimatedTimeSeconds: 15,
    marks: 0.5,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Discipline", "Focus"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Analyze", targetTrait: "Discipline" },
  },
  {
    id: "q_disc_05",
    stage: "personality",
    domain: "Discipline & Responsibility",
    subDomain: "Environment Organization",
    difficulty: "Easy",
    type: "likert",
    questionText: "I keep my study or work environment organized and clutter-free.",
    estimatedTimeSeconds: 15,
    marks: 0.5,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Orderliness", "Discipline"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Consistency" },
  },
  {
    id: "q_disc_06",
    stage: "personality",
    domain: "Discipline & Responsibility",
    subDomain: "Commitment Follow-Through",
    difficulty: "Hard",
    type: "likert",
    questionText: "I follow through on commitments even when I lose initial motivation or enthusiasm.",
    estimatedTimeSeconds: 15,
    marks: 0.5,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Persistence", "Reliability"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Reliability" },
  },
  {
    id: "q_disc_07",
    stage: "personality",
    domain: "Discipline & Responsibility",
    subDomain: "Daily Preparation",
    difficulty: "Easy",
    type: "likert",
    questionText: "I plan my day before starting work or studies.",
    estimatedTimeSeconds: 15,
    marks: 0.5,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Planning", "Productivity"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Discipline" },
  },
  {
    id: "q_disc_08",
    stage: "personality",
    domain: "Discipline & Responsibility",
    subDomain: "Self-Supervision",
    difficulty: "Hard",
    type: "likert",
    questionText: "I remain disciplined and productive even when no one is monitoring or evaluating me.",
    estimatedTimeSeconds: 15,
    marks: 0.5,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Autonomy", "Discipline"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Autonomy" },
  },

  // ================= B. INTEGRITY & ETHICS (Q9-Q13: 3 Marks) =================
  {
    id: "q_int_09",
    stage: "personality",
    domain: "Integrity & Ethics",
    subDomain: "Accountability",
    difficulty: "Medium",
    type: "likert",
    questionText: "I admit my mistakes immediately instead of blaming others or making excuses.",
    estimatedTimeSeconds: 15,
    marks: 0.6,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Integrity", "Accountability"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Integrity" },
  },
  {
    id: "q_int_10",
    stage: "personality",
    domain: "Integrity & Ethics",
    subDomain: "Honor & Respect",
    difficulty: "Easy",
    type: "likert",
    questionText: "I return borrowed items, funds, or commitments on time.",
    estimatedTimeSeconds: 15,
    marks: 0.6,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Trustworthiness", "Integrity"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Reliability" },
  },
  {
    id: "q_int_11",
    stage: "personality",
    domain: "Integrity & Ethics",
    subDomain: "Uncompromising Honesty",
    difficulty: "Hard",
    type: "likert",
    questionText: "I remain honest even when dishonesty could easily benefit me without being caught.",
    estimatedTimeSeconds: 15,
    marks: 0.6,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Ethics", "Honesty"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Integrity" },
  },
  {
    id: "q_int_12",
    stage: "personality",
    domain: "Integrity & Ethics",
    subDomain: "Confidentiality",
    difficulty: "Medium",
    type: "likert",
    questionText: "I respect and protect confidential information shared with me.",
    estimatedTimeSeconds: 15,
    marks: 0.6,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Confidentiality", "Trust"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Trustworthiness" },
  },
  {
    id: "q_int_13",
    stage: "personality",
    domain: "Integrity & Ethics",
    subDomain: "Ethical Standards",
    difficulty: "Hard",
    type: "likert",
    questionText: "I refuse shortcuts that compromise ethical principles, even under high pressure.",
    estimatedTimeSeconds: 15,
    marks: 0.6,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Ethics", "Principles"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Integrity" },
  },

  // ================= C. HEALTH & LIFESTYLE HABITS (Q14-Q18: 2 Marks) =================
  {
    id: "q_hl_14",
    stage: "personality",
    domain: "Health & Lifestyle Habits",
    subDomain: "Physical Exercise",
    difficulty: "Easy",
    type: "frequency",
    questionText: "How often do you exercise or engage in physical workouts per week?",
    estimatedTimeSeconds: 15,
    marks: 0.4,
    options: [
      { id: "ex_1", text: "Never", weight: 1 },
      { id: "ex_2", text: "Monthly", weight: 2 },
      { id: "ex_3", text: "1-2 times/week", weight: 3 },
      { id: "ex_4", text: "3-4 times/week", weight: 4 },
      { id: "ex_5", text: "Daily", weight: 5 },
    ],
    scoringRules: "Frequency scale measuring active fitness routines.",
    tags: ["Health", "Fitness"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Health Consciousness" },
  },
  {
    id: "q_hl_15",
    stage: "personality",
    domain: "Health & Lifestyle Habits",
    subDomain: "Rest & Sleep Quality",
    difficulty: "Easy",
    type: "likert",
    questionText: "I usually sleep 7–8 hours most nights and wake up feeling refreshed.",
    estimatedTimeSeconds: 15,
    marks: 0.4,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Sleep", "Recovery"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Health Consciousness" },
  },
  {
    id: "q_hl_16",
    stage: "personality",
    domain: "Health & Lifestyle Habits",
    subDomain: "Dietary Awareness",
    difficulty: "Easy",
    type: "likert",
    questionText: "I pay deliberate attention to maintaining a balanced, healthy diet.",
    estimatedTimeSeconds: 15,
    marks: 0.4,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Nutrition", "Health"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Health Consciousness" },
  },
  {
    id: "q_hl_17",
    stage: "personality",
    domain: "Health & Lifestyle Habits",
    subDomain: "Mindfulness & Recovery",
    difficulty: "Medium",
    type: "likert",
    questionText: "I meditate, pray, or practice mindfulness regularly to clear my mind.",
    estimatedTimeSeconds: 15,
    marks: 0.4,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Mindfulness", "MentalHealth"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Emotional Resilience" },
  },
  {
    id: "q_hl_18",
    stage: "personality",
    domain: "Health & Lifestyle Habits",
    subDomain: "Harm Avoidance",
    difficulty: "Medium",
    type: "likert",
    questionText: "I avoid harmful habits such as smoking or excessive alcohol consumption.",
    estimatedTimeSeconds: 15,
    marks: 0.4,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Lifestyle", "Longevity"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Health Consciousness" },
  },

  // ================= D. FINANCIAL BEHAVIOUR (Q19-Q23: 2 Marks) =================
  {
    id: "q_fin_19",
    stage: "personality",
    domain: "Financial Behaviour",
    subDomain: "Budgeting & Tracking",
    difficulty: "Easy",
    type: "likert",
    questionText: "I maintain a monthly budget for my income, savings, and expenses.",
    estimatedTimeSeconds: 15,
    marks: 0.4,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Finance", "Budgeting"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Financial Responsibility" },
  },
  {
    id: "q_fin_20",
    stage: "personality",
    domain: "Financial Behaviour",
    subDomain: "Systematic Savings",
    difficulty: "Easy",
    type: "likert",
    questionText: "I regularly save a fixed portion of my monthly income before spending.",
    estimatedTimeSeconds: 15,
    marks: 0.4,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Finance", "Savings"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Financial Responsibility" },
  },
  {
    id: "q_fin_21",
    stage: "personality",
    domain: "Financial Behaviour",
    subDomain: "Investment & Wealth Growth",
    difficulty: "Medium",
    type: "yes_no",
    questionText: "Do you currently invest money in financial growth instruments (e.g., stocks, mutual funds, real estate, SIPs) for your long-term future?",
    estimatedTimeSeconds: 15,
    marks: 0.4,
    options: [
      { id: "yn_no", text: "No", weight: 1 },
      { id: "yn_yes", text: "Yes", weight: 5 },
    ],
    scoringRules: "Binary active investment indicator.",
    tags: ["Investing", "Wealth"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Financial Responsibility" },
  },
  {
    id: "q_fin_22",
    stage: "personality",
    domain: "Financial Behaviour",
    subDomain: "Financial Literacy",
    difficulty: "Medium",
    type: "likert",
    questionText: "I understand the basics of personal finance, compounding, and inflation.",
    estimatedTimeSeconds: 15,
    marks: 0.4,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Literacy", "Finance"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Understand", targetTrait: "Financial Responsibility" },
  },
  {
    id: "q_fin_23",
    stage: "personality",
    domain: "Financial Behaviour",
    subDomain: "Prudent Spending",
    difficulty: "Easy",
    type: "likert",
    questionText: "I think carefully and compare options before making expensive or non-essential purchases.",
    estimatedTimeSeconds: 15,
    marks: 0.4,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Prudence", "Finance"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Financial Responsibility" },
  },

  // ================= E. LEADERSHIP & INITIATIVE (Q24-Q28: 3 Marks) =================
  {
    id: "q_lead_24",
    stage: "personality",
    domain: "Leadership & Initiative",
    subDomain: "Proactive Initiative",
    difficulty: "Medium",
    type: "likert",
    questionText: "I naturally take initiative when work or problem-solving needs to be done without waiting to be asked.",
    estimatedTimeSeconds: 15,
    marks: 0.6,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Initiative", "Leadership"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Leadership" },
  },
  {
    id: "q_lead_25",
    stage: "personality",
    domain: "Leadership & Initiative",
    subDomain: "Team Direction",
    difficulty: "Medium",
    type: "likert",
    questionText: "I am comfortable leading a team and guiding others toward a shared vision.",
    estimatedTimeSeconds: 15,
    marks: 0.6,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Leadership", "Management"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Leadership" },
  },
  {
    id: "q_lead_26",
    stage: "personality",
    domain: "Leadership & Initiative",
    subDomain: "Inspirational Motivation",
    difficulty: "Hard",
    type: "likert",
    questionText: "I can effectively motivate and reassure team members during high-stress or difficult situations.",
    estimatedTimeSeconds: 15,
    marks: 0.6,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Motivation", "Leadership"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Leadership" },
  },
  {
    id: "q_lead_27",
    stage: "personality",
    domain: "Leadership & Initiative",
    subDomain: "Outcome Responsibility",
    difficulty: "Hard",
    type: "likert",
    questionText: "I accept full responsibility for team outcomes and project results.",
    estimatedTimeSeconds: 15,
    marks: 0.6,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Accountability", "Leadership"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Responsibility" },
  },
  {
    id: "q_lead_28",
    stage: "personality",
    domain: "Leadership & Initiative",
    subDomain: "Confident Decision Making",
    difficulty: "Medium",
    type: "likert",
    questionText: "I make decisions confidently after gathering necessary information.",
    estimatedTimeSeconds: 15,
    marks: 0.6,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Decisiveness", "Leadership"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Analyze", targetTrait: "Confidence" },
  },

  // ================= F. EMOTIONAL INTELLIGENCE (Q29-Q33: 3 Marks) =================
  {
    id: "q_eq_29",
    stage: "personality",
    domain: "Emotional Intelligence",
    subDomain: "Stress Calmness",
    difficulty: "Medium",
    type: "likert",
    questionText: "I remain calm and compose my thoughts during stressful or high-pressure situations.",
    estimatedTimeSeconds: 15,
    marks: 0.6,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["EQ", "StressControl"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Emotional Intelligence" },
  },
  {
    id: "q_eq_30",
    stage: "personality",
    domain: "Emotional Intelligence",
    subDomain: "Empathy & Awareness",
    difficulty: "Easy",
    type: "likert",
    questionText: "I accurately understand the emotions, non-verbal cues, and feelings of people around me.",
    estimatedTimeSeconds: 15,
    marks: 0.6,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Empathy", "EQ"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Understand", targetTrait: "Social Intelligence" },
  },
  {
    id: "q_eq_31",
    stage: "personality",
    domain: "Emotional Intelligence",
    subDomain: "Emotional Regulation",
    difficulty: "Hard",
    type: "likert",
    questionText: "I pause and control my emotional impulses before reacting to frustrating situations.",
    estimatedTimeSeconds: 15,
    marks: 0.6,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["SelfRegulation", "EQ"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Emotional Intelligence" },
  },
  {
    id: "q_eq_32",
    stage: "personality",
    domain: "Emotional Intelligence",
    subDomain: "Setback Resilience",
    difficulty: "Medium",
    type: "likert",
    questionText: "I recover quickly and regain focus after unexpected personal or professional setbacks.",
    estimatedTimeSeconds: 15,
    marks: 0.6,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Resilience", "EQ"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Growth Potential" },
  },
  {
    id: "q_eq_33",
    stage: "personality",
    domain: "Emotional Intelligence",
    subDomain: "Respectful Communication",
    difficulty: "Easy",
    type: "likert",
    questionText: "I remain respectful, polite, and constructive even during intense disagreements.",
    estimatedTimeSeconds: 15,
    marks: 0.6,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Respect", "EQ"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Social Intelligence" },
  },

  // ================= G. TEAMWORK & SOCIAL BEHAVIOUR (Q34-Q38: 2 Marks) =================
  {
    id: "q_team_34",
    stage: "personality",
    domain: "Teamwork & Social Behaviour",
    subDomain: "Diversity Inclusion",
    difficulty: "Easy",
    type: "likert",
    questionText: "I genuinely enjoy working with people from diverse backgrounds, disciplines, and cultures.",
    estimatedTimeSeconds: 15,
    marks: 0.4,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Teamwork", "Inclusion"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Understand", targetTrait: "Teamwork" },
  },
  {
    id: "q_team_35",
    stage: "personality",
    domain: "Teamwork & Social Behaviour",
    subDomain: "Active Listening",
    difficulty: "Easy",
    type: "likert",
    questionText: "I actively listen to understand others' perspectives before formulating my response.",
    estimatedTimeSeconds: 15,
    marks: 0.4,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Listening", "Communication"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Understand", targetTrait: "Teamwork" },
  },
  {
    id: "q_team_36",
    stage: "personality",
    domain: "Teamwork & Social Behaviour",
    subDomain: "Altruistic Collaboration",
    difficulty: "Medium",
    type: "likert",
    questionText: "I willingly assist teammates with their workload without expecting immediate personal rewards.",
    estimatedTimeSeconds: 15,
    marks: 0.4,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Helpfulness", "Teamwork"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Teamwork" },
  },
  {
    id: "q_team_37",
    stage: "personality",
    domain: "Teamwork & Social Behaviour",
    subDomain: "Feedback Receptivity",
    difficulty: "Medium",
    type: "likert",
    questionText: "I value constructive criticism from others and use it to improve my performance.",
    estimatedTimeSeconds: 15,
    marks: 0.4,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Feedback", "Growth"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Growth Potential" },
  },
  {
    id: "q_team_38",
    stage: "personality",
    domain: "Teamwork & Social Behaviour",
    subDomain: "Conflict Resolution",
    difficulty: "Hard",
    type: "sjt",
    scenarioText: "Two key members of your project team are locked in a heated dispute regarding API architecture, causing the sprint deadline to slip.",
    questionText: "How do you resolve the situation?",
    estimatedTimeSeconds: 30,
    marks: 0.4,
    options: [
      { id: "sjt_team_1", text: "Facilitate a structured discussion focusing on data, trade-offs, and shared goals.", weight: 5, isCorrect: true },
      { id: "sjt_team_2", text: "Tell them to figure it out on their own time and stop delaying the project.", weight: 1 },
      { id: "sjt_team_3", text: "Pick one person's side quickly to move forward regardless of technical quality.", weight: 2 },
      { id: "sjt_team_4", text: "Escalate the issue to executive management immediately.", weight: 3 },
    ],
    scoringRules: "Situational judgment conflict resolution test.",
    explanation: "Structured data-driven mediation preserves team harmony and optimal technical quality.",
    tags: ["ConflictResolution", "Teamwork"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Teamwork" },
  },

  // ================= H. LEARNING & CURIOSITY (Q39-Q43: 2 Marks) =================
  {
    id: "q_learn_39",
    stage: "personality",
    domain: "Learning & Curiosity",
    subDomain: "Reading & Intellectual Pursuit",
    difficulty: "Easy",
    type: "likert",
    questionText: "I regularly read books, research papers, or educational content to expand my knowledge.",
    estimatedTimeSeconds: 15,
    marks: 0.4,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Reading", "Curiosity"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Remember", targetTrait: "Learning Orientation" },
  },
  {
    id: "q_learn_40",
    stage: "personality",
    domain: "Learning & Curiosity",
    subDomain: "Current Affairs & Industry Trends",
    difficulty: "Easy",
    type: "likert",
    questionText: "I stay updated with current global news, technology trends, and industry developments.",
    estimatedTimeSeconds: 15,
    marks: 0.4,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["News", "Awareness"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Understand", targetTrait: "Curiosity" },
  },
  {
    id: "q_learn_41",
    stage: "personality",
    domain: "Learning & Curiosity",
    subDomain: "New Skill Acquisition",
    difficulty: "Medium",
    type: "likert",
    questionText: "I genuinely enjoy learning complex new skills and exploring unfamiliar domains.",
    estimatedTimeSeconds: 15,
    marks: 0.4,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Upskilling", "Curiosity"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Learning Orientation" },
  },
  {
    id: "q_learn_42",
    stage: "personality",
    domain: "Learning & Curiosity",
    subDomain: "Formal Upskilling Courses",
    difficulty: "Medium",
    type: "yes_no",
    questionText: "Do you regularly complete online courses, certifications, or workshops to upgrade your capability?",
    estimatedTimeSeconds: 15,
    marks: 0.4,
    options: [
      { id: "yn_course_no", text: "No", weight: 1 },
      { id: "yn_course_yes", text: "Yes", weight: 5 },
    ],
    scoringRules: "Binary course completion tracking.",
    tags: ["Courses", "Upskilling"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Learning Orientation" },
  },
  {
    id: "q_learn_43",
    stage: "personality",
    domain: "Learning & Curiosity",
    subDomain: "Proactive Knowledge Pursuit",
    difficulty: "Hard",
    type: "likert",
    questionText: "I actively seek out feedback and research topics deeply to continuously improve myself.",
    estimatedTimeSeconds: 15,
    marks: 0.4,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Research", "Growth"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Analyze", targetTrait: "Growth Potential" },
  },

  // ================= I. PRODUCTIVITY & TIME MANAGEMENT (Q44-Q47: 2 Marks) =================
  {
    id: "q_prod_44",
    stage: "personality",
    domain: "Productivity & Time Management",
    subDomain: "Task Prioritization",
    difficulty: "Easy",
    type: "likert",
    questionText: "I prioritize important high-impact tasks over urgent but low-value distractions.",
    estimatedTimeSeconds: 15,
    marks: 0.5,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Prioritization", "Productivity"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Productivity" },
  },
  {
    id: "q_prod_45",
    stage: "personality",
    domain: "Productivity & Time Management",
    subDomain: "Digital Distraction Control",
    difficulty: "Medium",
    type: "likert",
    questionText: "I limit unnecessary social media and smartphone notifications while working.",
    estimatedTimeSeconds: 15,
    marks: 0.5,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Focus", "Productivity"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Productivity" },
  },
  {
    id: "q_prod_46",
    stage: "personality",
    domain: "Productivity & Time Management",
    subDomain: "Goal Review Cadence",
    difficulty: "Medium",
    type: "likert",
    questionText: "I review my personal and professional goals regularly to ensure alignment.",
    estimatedTimeSeconds: 15,
    marks: 0.5,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["GoalSetting", "Alignment"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Productivity" },
  },
  {
    id: "q_prod_47",
    stage: "personality",
    domain: "Productivity & Time Management",
    subDomain: "Deep Work Focus",
    difficulty: "Hard",
    type: "likert",
    questionText: "I maintain deep concentration for long periods without getting distracted.",
    estimatedTimeSeconds: 15,
    marks: 0.5,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["DeepWork", "Focus"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Productivity" },
  },

  // ================= J. SELF-AWARENESS & CONFIDENCE (Q48-Q50: 2 Marks) =================
  {
    id: "q_self_48",
    stage: "personality",
    domain: "Self-Awareness & Confidence",
    subDomain: "Self-Assessment Accuracy",
    difficulty: "Medium",
    type: "likert",
    questionText: "I accurately understand both my core strengths and my developmental weaknesses.",
    estimatedTimeSeconds: 15,
    marks: 0.67,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["SelfAwareness", "Introspection"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Understand", targetTrait: "Self-Awareness" },
  },
  {
    id: "q_self_49",
    stage: "personality",
    domain: "Self-Awareness & Confidence",
    subDomain: "Self-Efficacy & Belief",
    difficulty: "Medium",
    type: "likert",
    questionText: "I firmly believe I can achieve difficult goals through consistent hard work and strategy.",
    estimatedTimeSeconds: 15,
    marks: 0.67,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Confidence", "SelfEfficacy"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Confidence" },
  },
  {
    id: "q_self_50",
    stage: "personality",
    domain: "Self-Awareness & Confidence",
    subDomain: "Continuous Self-Refinement",
    difficulty: "Hard",
    type: "likert",
    questionText: "I regularly reflect on my personal growth and actively make changes to refine my behavior.",
    estimatedTimeSeconds: 15,
    marks: 0.66,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["SelfRefinement", "Growth"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Create", targetTrait: "Growth Potential" },
  },
];

// ================= STAGE 2: MINDSET ASSESSMENT (25 Questions → 20 Marks) =================
export const MINDSET_QUESTION_BANK: QuestionItem[] = [
  // --- A. GROWTH MINDSET (M1-M5 → 4 Marks, 0.8 each) ---
  {
    id: "m_gm_01",
    stage: "mindset",
    domain: "Growth Mindset",
    subDomain: "Effort & Ability Development",
    difficulty: "Easy",
    type: "likert",
    questionText: "I believe my fundamental abilities and intelligence can improve continuously through consistent effort and learning.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["GrowthMindset", "Learning"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Understand", targetTrait: "Growth Mindset" },
  },
  {
    id: "m_gm_02",
    stage: "mindset",
    domain: "Growth Mindset",
    subDomain: "Challenge Embracement",
    difficulty: "Medium",
    type: "likert",
    questionText: "I view difficult challenges as exciting opportunities to grow rather than threatening obstacles.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["GrowthMindset", "Challenges"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Adaptability" },
  },
  {
    id: "m_gm_03",
    stage: "mindset",
    domain: "Growth Mindset",
    subDomain: "Feedback Seeking",
    difficulty: "Medium",
    type: "likert",
    questionText: "I actively seek out constructive feedback from mentors and peers to improve my performance.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["GrowthMindset", "Feedback"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Growth Mindset" },
  },
  {
    id: "m_gm_04",
    stage: "mindset",
    domain: "Growth Mindset",
    subDomain: "Comfort Zone Expansion",
    difficulty: "Hard",
    type: "likert",
    questionText: "I enjoy acquiring complex skills that push me outside my current comfort zone.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["GrowthMindset", "SkillBuilding"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Create", targetTrait: "Adaptability" },
  },
  {
    id: "m_gm_05",
    stage: "mindset",
    domain: "Growth Mindset",
    subDomain: "Continuous Learning Priority",
    difficulty: "Easy",
    type: "likert",
    questionText: "I believe continuous learning and unlearning are essential for long-term career success.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["GrowthMindset", "LifelongLearning"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Understand", targetTrait: "Growth Mindset" },
  },

  // --- B. DISCIPLINE & CONSISTENCY (M6-M10 → 4 Marks, 0.8 each) ---
  {
    id: "m_dc_06",
    stage: "mindset",
    domain: "Discipline & Consistency",
    subDomain: "Unmotivated Execution",
    difficulty: "Medium",
    type: "likert",
    questionText: "I execute my daily goals and tasks even on days when I feel unmotivated or low energy.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Discipline", "Consistency"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Discipline" },
  },
  {
    id: "m_dc_07",
    stage: "mindset",
    domain: "Discipline & Consistency",
    subDomain: "Long-term Momentum",
    difficulty: "Hard",
    type: "likert",
    questionText: "I maintain steady output and work consistency over extended months without burning out.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Consistency", "Stamina"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Analyze", targetTrait: "Consistency" },
  },
  {
    id: "m_dc_08",
    stage: "mindset",
    domain: "Discipline & Consistency",
    subDomain: "Delayed Gratification",
    difficulty: "Medium",
    type: "likert",
    questionText: "I complete important deep work before rewarding myself with leisure or entertainment activities.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["DelayedGratification", "Discipline"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Discipline" },
  },
  {
    id: "m_dc_09",
    stage: "mindset",
    domain: "Discipline & Consistency",
    subDomain: "Patience & Perseverance",
    difficulty: "Medium",
    type: "likert",
    questionText: "I avoid abandoning long-term projects when visible progress is slower than initially expected.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Perseverance", "Patience"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Consistency" },
  },
  {
    id: "m_dc_10",
    stage: "mindset",
    domain: "Discipline & Consistency",
    subDomain: "Habit Audit & Refinement",
    difficulty: "Easy",
    type: "likert",
    questionText: "I regularly audit and refine my daily habits to eliminate unproductive behaviors.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["HabitAudit", "SelfRefinement"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Discipline" },
  },

  // --- C. GRIT & RESILIENCE (M11-M15 → 4 Marks, 0.8 each) ---
  {
    id: "m_gr_11",
    stage: "mindset",
    domain: "Grit & Resilience",
    subDomain: "Failure Rebound Velocity",
    difficulty: "Medium",
    type: "likert",
    questionText: "I recover my focus and optimism quickly after major disappointments or project failures.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Resilience", "Grit"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Resilience" },
  },
  {
    id: "m_gr_12",
    stage: "mindset",
    domain: "Grit & Resilience",
    subDomain: "Long-term Goal Persistence",
    difficulty: "Hard",
    type: "likert",
    questionText: "I stay single-mindedly focused on long-term multi-year goals despite temporary short-term setbacks.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Grit", "Focus"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Grit" },
  },
  {
    id: "m_gr_13",
    stage: "mindset",
    domain: "Grit & Resilience",
    subDomain: "Adversity Positivity",
    difficulty: "Medium",
    type: "likert",
    questionText: "I maintain a constructive, solution-oriented mindset even during highly chaotic or stressful periods.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Resilience", "Positivity"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Analyze", targetTrait: "Resilience" },
  },
  {
    id: "m_gr_14",
    stage: "mindset",
    domain: "Grit & Resilience",
    subDomain: "Mistake Extraction",
    difficulty: "Easy",
    type: "likert",
    questionText: "I extract key lessons from my mistakes instead of dwelling on negative emotions or regret.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["LearningFromMistakes", "Resilience"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Understand", targetTrait: "Resilience" },
  },
  {
    id: "m_gr_15",
    stage: "mindset",
    domain: "Grit & Resilience",
    subDomain: "Skepticism Conviction",
    difficulty: "Hard",
    type: "likert",
    questionText: "I continue working relentlessly toward my vision even when others express doubt or skepticism.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Conviction", "Grit"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Grit" },
  },

  // --- D. GOAL ORIENTATION & SELF-BELIEF (M16-M20 → 4 Marks, 0.8 each) ---
  {
    id: "m_gb_16",
    stage: "mindset",
    domain: "Goal Orientation & Self-Belief",
    subDomain: "Explicit Goal Setting",
    difficulty: "Easy",
    type: "likert",
    questionText: "I set clear, measurable, and ambitious personal and professional goals for myself.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["GoalSetting", "Ambition"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Goal Orientation" },
  },
  {
    id: "m_gb_17",
    stage: "mindset",
    domain: "Goal Orientation & Self-Belief",
    subDomain: "Self-Efficacy Conviction",
    difficulty: "Medium",
    type: "likert",
    questionText: "I firmly believe in my ability to achieve high-impact goals through strategic planning and dedication.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["SelfBelief", "SelfEfficacy"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Self-Belief" },
  },
  {
    id: "m_gb_18",
    stage: "mindset",
    domain: "Goal Orientation & Self-Belief",
    subDomain: "Progress Tracking",
    difficulty: "Easy",
    type: "likert",
    questionText: "I systematically track and measure my progress toward key personal milestones.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Tracking", "Accountability"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Goal Orientation" },
  },
  {
    id: "m_gb_19",
    stage: "mindset",
    domain: "Goal Orientation & Self-Belief",
    subDomain: "High Standard Challenge",
    difficulty: "Medium",
    type: "likert",
    questionText: "I regularly raise my personal performance bar to achieve higher benchmarks than before.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Excellence", "SelfBelief"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Analyze", targetTrait: "Self-Belief" },
  },
  {
    id: "m_gb_20",
    stage: "mindset",
    domain: "Goal Orientation & Self-Belief",
    subDomain: "Locus of Control",
    difficulty: "Hard",
    type: "likert",
    questionText: "I take 100% personal responsibility for creating my own success rather than relying on luck or circumstances.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["InternalLocus", "SelfBelief"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Self-Belief" },
  },

  // --- E. ENTREPRENEURIAL & FINANCIAL MINDSET (M21-M25 → 4 Marks, 0.8 each) ---
  {
    id: "m_ef_21",
    stage: "mindset",
    domain: "Entrepreneurial & Financial Mindset",
    subDomain: "Value Creation Spotting",
    difficulty: "Medium",
    type: "likert",
    questionText: "I actively look for opportunities to solve inefficiencies and create economic value for others.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Entrepreneurship", "ValueCreation"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Create", targetTrait: "Entrepreneurial Mindset" },
  },
  {
    id: "m_ef_22",
    stage: "mindset",
    domain: "Entrepreneurial & Financial Mindset",
    subDomain: "Long-Term Capital Orientation",
    difficulty: "Medium",
    type: "likert",
    questionText: "I prioritize building long-term financial freedom and asset ownership over short-term impulsive spending.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["FinancialMindset", "AssetBuilding"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Financial Mindset" },
  },
  {
    id: "m_ef_23",
    stage: "mindset",
    domain: "Entrepreneurial & Financial Mindset",
    subDomain: "Calculated Risk Taking",
    difficulty: "Hard",
    type: "likert",
    questionText: "I am willing to take well-reasoned, calculated risks when the upside potential justifies it.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["RiskTaking", "Entrepreneurship"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Analyze", targetTrait: "Entrepreneurial Mindset" },
  },
  {
    id: "m_ef_24",
    stage: "mindset",
    domain: "Entrepreneurial & Financial Mindset",
    subDomain: "Creative Problem Solving",
    difficulty: "Medium",
    type: "likert",
    questionText: "I enjoy solving complex problems in creative, non-traditional, and innovative ways.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Innovation", "ProblemSolving"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Create", targetTrait: "Adaptability" },
  },
  {
    id: "m_ef_25",
    stage: "mindset",
    domain: "Entrepreneurial & Financial Mindset",
    subDomain: "Future Paradigm Adaptability",
    difficulty: "Hard",
    type: "likert",
    questionText: "I believe adaptability and rapid unlearning are the single most critical skills for future technological success.",
    estimatedTimeSeconds: 15,
    marks: 0.8,
    options: likertOptions,
    scoringRules: "5-point Likert scale.",
    tags: ["Adaptability", "FutureProof"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Adaptability" },
  },
];

// ================= STAGE 3: DECISION MAKING ASSESSMENT (15 Questions → 15 Marks) =================
export const DECISION_QUESTION_BANK: QuestionItem[] = [
  // Question 1 – Financial Planning
  {
    id: "d_fin_01",
    stage: "decision",
    domain: "Financial Decision Making",
    subDomain: "Inheritance Capital Allocation",
    difficulty: "Medium",
    type: "sjt",
    scenarioText: "You receive an unexpected ₹10 lakh inheritance.",
    questionText: "What would you most likely do?",
    estimatedTimeSeconds: 25,
    marks: 1.0,
    options: [
      { id: "d1_a", text: "A. Spend most of it on lifestyle upgrades.", weight: 1 },
      { id: "d1_b", text: "B. Invest the entire amount immediately.", weight: 2 },
      { id: "d1_c", text: "C. Build an emergency fund, repay any high-interest debt, invest a significant portion, and keep some cash for future needs.", weight: 5, isCorrect: true },
      { id: "d1_d", text: "D. Keep all the money in a savings account.", weight: 3.75 },
    ],
    scoringRules: "Weighted decision SJT scoring (1.0 Best, 0.75 Good, 0.25 Weak, 0 Poor).",
    explanation: "Option C balances liquidity, debt clearance, and compound investment growth.",
    tags: ["FinancialPlanning", "CapitalAllocation"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Financial Decision Making" },
  },
  // Question 2 – Career Growth
  {
    id: "d_car_02",
    stage: "decision",
    domain: "Career Judgment",
    subDomain: "Career Opportunity Evaluation",
    difficulty: "Medium",
    type: "sjt",
    scenarioText: "You receive two job offers: Offer A (Higher salary but limited learning) vs Offer B (Lower salary but excellent mentorship & growth).",
    questionText: "Which would you choose?",
    estimatedTimeSeconds: 25,
    marks: 1.0,
    options: [
      { id: "d2_a", text: "A. Offer A (Higher salary, limited growth)", weight: 2 },
      { id: "d2_b", text: "B. Offer B (Lower salary, excellent mentorship & career growth)", weight: 5, isCorrect: true },
      { id: "d2_c", text: "C. Reject both and continue searching", weight: 3.75 },
      { id: "d2_d", text: "D. Choose based only on the company's reputation", weight: 1 },
    ],
    scoringRules: "Weighted decision SJT scoring.",
    explanation: "Mentorship and career trajectory compound human capital faster than initial base salary.",
    tags: ["CareerGrowth", "LongTermVision"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Career Judgment" },
  },
  // Question 3 – Team Conflict
  {
    id: "d_team_03",
    stage: "decision",
    domain: "Leadership Judgment",
    subDomain: "Dispute Mediation",
    difficulty: "Medium",
    type: "sjt",
    scenarioText: "Two members of your team strongly disagree on how to solve an important technical problem.",
    questionText: "What do you do?",
    estimatedTimeSeconds: 25,
    marks: 1.0,
    options: [
      { id: "d3_a", text: "A. Support the person you know better.", weight: 1 },
      { id: "d3_b", text: "B. Let them solve it themselves.", weight: 2 },
      { id: "d3_c", text: "C. Listen to both perspectives, evaluate the facts, and facilitate a fair decision.", weight: 5, isCorrect: true },
      { id: "d3_d", text: "D. Ask your manager to decide immediately.", weight: 3.75 },
    ],
    scoringRules: "Weighted decision SJT scoring.",
    explanation: "Data-driven objective facilitation ensures optimal decision quality and team alignment.",
    tags: ["ConflictResolution", "Leadership"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Leadership Judgment" },
  },
  // Question 4 – Ethical Decision
  {
    id: "d_eth_04",
    stage: "decision",
    domain: "Ethical Reasoning",
    subDomain: "Workplace Credit Integrity",
    difficulty: "Hard",
    type: "sjt",
    scenarioText: "You notice a colleague claiming credit for work completed by someone else.",
    questionText: "What would you do?",
    estimatedTimeSeconds: 25,
    marks: 1.0,
    options: [
      { id: "d4_a", text: "A. Ignore it.", weight: 1 },
      { id: "d4_b", text: "B. Publicly accuse the colleague.", weight: 2 },
      { id: "d4_c", text: "C. Discuss the issue privately and, if necessary, report it through the appropriate channel.", weight: 5, isCorrect: true },
      { id: "d4_d", text: "D. Tell your friends but take no action.", weight: 1 },
    ],
    scoringRules: "Weighted decision SJT scoring.",
    explanation: "Private dialogue followed by formal ethics channels balances discretion with integrity.",
    tags: ["Ethics", "Integrity"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Ethical Reasoning" },
  },
  // Question 5 – Time Management
  {
    id: "d_tm_05",
    stage: "decision",
    domain: "Time Management",
    subDomain: "Simultaneous Deadline Management",
    difficulty: "Medium",
    type: "sjt",
    scenarioText: "You have three important deadlines due on the exact same day.",
    questionText: "How would you handle them?",
    estimatedTimeSeconds: 25,
    marks: 1.0,
    options: [
      { id: "d5_a", text: "A. Complete whichever task seems easiest first.", weight: 2 },
      { id: "d5_b", text: "B. Work randomly and hope to finish everything.", weight: 1 },
      { id: "d5_c", text: "C. Prioritize tasks based on urgency and importance, then create a plan.", weight: 5, isCorrect: true },
      { id: "d5_d", text: "D. Ask for deadline extensions without attempting the work.", weight: 1 },
    ],
    scoringRules: "Weighted decision SJT scoring.",
    explanation: "Eisenhower matrix prioritization (Urgent vs Important) maximizes output value under crunch.",
    tags: ["TimeManagement", "Prioritization"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Time Management" },
  },
  // Question 6 – Business Opportunity
  {
    id: "d_biz_06",
    stage: "decision",
    domain: "Risk Assessment",
    subDomain: "Due Diligence",
    difficulty: "Hard",
    type: "sjt",
    scenarioText: "A friend invites you to invest in a startup promising very high returns but providing very little financial information.",
    questionText: "What would you do?",
    estimatedTimeSeconds: 25,
    marks: 1.0,
    options: [
      { id: "d6_a", text: "A. Invest immediately.", weight: 1 },
      { id: "d6_b", text: "B. Decline without asking questions.", weight: 2 },
      { id: "d6_c", text: "C. Conduct due diligence before making a decision.", weight: 5, isCorrect: true },
      { id: "d6_d", text: "D. Borrow money to invest.", weight: 1 },
    ],
    scoringRules: "Weighted decision SJT scoring.",
    explanation: "Rigorous due diligence prevents capital loss in unverified ventures.",
    tags: ["DueDiligence", "RiskAssessment"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Analyze", targetTrait: "Risk Assessment" },
  },
  // Question 7 – Learning & Development
  {
    id: "d_ld_07",
    stage: "decision",
    domain: "Strategic Thinking",
    subDomain: "Proactive Skill Adoption",
    difficulty: "Easy",
    type: "sjt",
    scenarioText: "A new technology becomes widely used in your industry.",
    questionText: "What would you most likely do?",
    estimatedTimeSeconds: 25,
    marks: 1.0,
    options: [
      { id: "d7_a", text: "A. Ignore it because your current skills are enough.", weight: 1 },
      { id: "d7_b", text: "B. Wait until your employer requires it.", weight: 2 },
      { id: "d7_c", text: "C. Learn it proactively to stay competitive.", weight: 5, isCorrect: true },
      { id: "d7_d", text: "D. Assume it is just another short-term trend.", weight: 1 },
    ],
    scoringRules: "Weighted decision SJT scoring.",
    explanation: "Proactive skill acquisition maintains human capital competitive advantage.",
    tags: ["ContinuousLearning", "StrategicThinking"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Strategic Thinking" },
  },
  // Question 8 – Crisis Management
  {
    id: "d_cm_08",
    stage: "decision",
    domain: "Crisis Management",
    subDomain: "Post-Mortem & Recovery",
    difficulty: "Hard",
    type: "sjt",
    scenarioText: "A major project fails despite your team's best efforts.",
    questionText: "What is your first response?",
    estimatedTimeSeconds: 25,
    marks: 1.0,
    options: [
      { id: "d8_a", text: "A. Blame external circumstances.", weight: 1 },
      { id: "d8_b", text: "B. Blame individual team members.", weight: 1 },
      { id: "d8_c", text: "C. Analyze what happened, identify lessons learned, and develop a recovery plan.", weight: 5, isCorrect: true },
      { id: "d8_d", text: "D. Move on without reviewing the project.", weight: 1 },
    ],
    scoringRules: "Weighted decision SJT scoring.",
    explanation: "Blameless post-mortems extract institutional wisdom and build resilient recovery plans.",
    tags: ["CrisisManagement", "PostMortem"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Crisis Management" },
  },
  // Question 9 – Personal Finance
  {
    id: "d_pf_09",
    stage: "decision",
    domain: "Financial Decision Making",
    subDomain: "Expense Crisis Adjustment",
    difficulty: "Medium",
    type: "sjt",
    scenarioText: "Your monthly expenses suddenly increase unexpectedly.",
    questionText: "What do you do?",
    estimatedTimeSeconds: 25,
    marks: 1.0,
    options: [
      { id: "d9_a", text: "A. Use credit cards without a repayment plan.", weight: 1 },
      { id: "d9_b", text: "B. Reduce unnecessary spending and adjust your budget.", weight: 5, isCorrect: true },
      { id: "d9_c", text: "C. Stop saving entirely.", weight: 2 },
      { id: "d9_d", text: "D. Borrow money immediately from friends.", weight: 1 },
    ],
    scoringRules: "Weighted decision SJT scoring.",
    explanation: "Immediate budget trimming protects solvency without incurring high-interest debt.",
    tags: ["PersonalFinance", "Budgeting"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Financial Decision Making" },
  },
  // Question 10 – Leadership
  {
    id: "d_ld_10",
    stage: "decision",
    domain: "Leadership Judgment",
    subDomain: "Team Morale Recovery",
    difficulty: "Medium",
    type: "sjt",
    scenarioText: "Your team is losing motivation during a difficult project.",
    questionText: "What would you do?",
    estimatedTimeSeconds: 25,
    marks: 1.0,
    options: [
      { id: "d10_a", text: "A. Ignore the situation and focus only on your own work.", weight: 1 },
      { id: "d10_b", text: "B. Criticize the team for poor performance.", weight: 1 },
      { id: "d10_c", text: "C. Encourage open communication, support the team, and refocus everyone on shared goals.", weight: 5, isCorrect: true },
      { id: "d10_d", text: "D. Wait for someone else to solve the problem.", weight: 1 },
    ],
    scoringRules: "Weighted decision SJT scoring.",
    explanation: "Empathic, transparent leadership restores psychological safety and shared purpose.",
    tags: ["Leadership", "TeamMorale"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Leadership Judgment" },
  },
  // Question 11 – Risk Management
  {
    id: "d_rm_11",
    stage: "decision",
    domain: "Risk Assessment",
    subDomain: "Proactive Risk Mitigation",
    difficulty: "Hard",
    type: "sjt",
    scenarioText: "You identify a significant risk that could delay an important project.",
    questionText: "What do you do?",
    estimatedTimeSeconds: 25,
    marks: 1.0,
    options: [
      { id: "d11_a", text: "A. Hope it doesn't happen.", weight: 1 },
      { id: "d11_b", text: "B. Ignore it because solving it is difficult.", weight: 1 },
      { id: "d11_c", text: "C. Inform stakeholders and create a mitigation plan.", weight: 5, isCorrect: true },
      { id: "d11_d", text: "D. Wait until the problem occurs.", weight: 1 },
    ],
    scoringRules: "Weighted decision SJT scoring.",
    explanation: "Early stakeholder alignment and contingency mitigation prevent project failure.",
    tags: ["RiskMitigation", "ProjectManagement"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Analyze", targetTrait: "Risk Assessment" },
  },
  // Question 12 – Innovation
  {
    id: "d_inn_12",
    stage: "decision",
    domain: "Innovation Mindset",
    subDomain: "Process Improvement Proposal",
    difficulty: "Medium",
    type: "sjt",
    scenarioText: "Your organization has always followed the same process, but you discover a better approach.",
    questionText: "What would you do?",
    estimatedTimeSeconds: 25,
    marks: 1.0,
    options: [
      { id: "d12_a", text: "A. Keep using the old process.", weight: 2 },
      { id: "d12_b", text: "B. Suggest and support implementing the improved approach with evidence.", weight: 5, isCorrect: true },
      { id: "d12_c", text: "C. Complain privately but do nothing.", weight: 1 },
      { id: "d12_d", text: "D. Ignore the opportunity.", weight: 1 },
    ],
    scoringRules: "Weighted decision SJT scoring.",
    explanation: "Data-backed evidence proposals drive organizational innovation without friction.",
    tags: ["Innovation", "ProcessOptimization"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Create", targetTrait: "Innovation Mindset" },
  },
  // Question 13 – Work-Life Balance
  {
    id: "d_wlb_13",
    stage: "decision",
    domain: "Personal Responsibility",
    subDomain: "Burnout Prevention",
    difficulty: "Medium",
    type: "sjt",
    scenarioText: "You have been working continuously for several weeks and feel mentally exhausted.",
    questionText: "What would you do?",
    estimatedTimeSeconds: 25,
    marks: 1.0,
    options: [
      { id: "d13_a", text: "A. Continue without making any changes.", weight: 1 },
      { id: "d13_b", text: "B. Quit your job immediately.", weight: 2 },
      { id: "d13_c", text: "C. Take appropriate rest, prioritize your workload, and return with a sustainable plan.", weight: 5, isCorrect: true },
      { id: "d13_d", text: "D. Ignore your health.", weight: 1 },
    ],
    scoringRules: "Weighted decision SJT scoring.",
    explanation: "Sustainable work practices prevent long-term physical and mental burnout.",
    tags: ["BurnoutPrevention", "WorkLifeBalance"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Personal Responsibility" },
  },
  // Question 14 – Customer Service
  {
    id: "d_cs_14",
    stage: "decision",
    domain: "Customer Orientation",
    subDomain: "De-escalation & Resolution",
    difficulty: "Medium",
    type: "sjt",
    scenarioText: "A customer is upset and speaks rudely to you about a problem.",
    questionText: "What would you do?",
    estimatedTimeSeconds: 25,
    marks: 1.0,
    options: [
      { id: "d14_a", text: "A. Respond with the same attitude.", weight: 1 },
      { id: "d14_b", text: "B. End the conversation.", weight: 2 },
      { id: "d14_c", text: "C. Stay calm, understand the issue, and work toward a solution.", weight: 5, isCorrect: true },
      { id: "d14_d", text: "D. Tell the customer it is not your responsibility.", weight: 1 },
    ],
    scoringRules: "Weighted decision SJT scoring.",
    explanation: "Calm de-escalation protects customer trust and resolves root causes.",
    tags: ["CustomerService", "DeEscalation"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Customer Orientation" },
  },
  // Question 15 – Long-Term Vision
  {
    id: "d_ltv_15",
    stage: "decision",
    domain: "Long-Term Thinking",
    subDomain: "Time Capital Investment",
    difficulty: "Easy",
    type: "sjt",
    scenarioText: "You have some free time each evening.",
    questionText: "How would you most likely use it?",
    estimatedTimeSeconds: 25,
    marks: 1.0,
    options: [
      { id: "d15_a", text: "A. Spend all the time on entertainment.", weight: 2 },
      { id: "d15_b", text: "B. Sleep early every day without any personal development.", weight: 2 },
      { id: "d15_c", text: "C. Balance rest with learning, skill development, or working toward long-term goals.", weight: 5, isCorrect: true },
      { id: "d15_d", text: "D. Decide each day without any plan.", weight: 1 },
    ],
    scoringRules: "Weighted decision SJT scoring.",
    explanation: "Balancing recovery with self-improvement builds sustainable long-term human capital.",
    tags: ["LongTermVision", "SelfDevelopment"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Long-Term Thinking" },
  },
];

// ================= STAGE 4: GENERAL AWARENESS ASSESSMENT (15 Questions → 15 Marks) =================
export const AWARENESS_QUESTION_BANK: QuestionItem[] = [
  {
    id: "a_econ_01",
    stage: "awareness",
    domain: "Economic Awareness",
    subDomain: "Inflation & Price Dynamics",
    difficulty: "Easy",
    type: "mcq",
    questionText: "What does inflation generally mean?",
    estimatedTimeSeconds: 20,
    marks: 1.0,
    options: [
      { id: "a1_a", text: "A. Increase in employment opportunities", weight: 1 },
      { id: "a1_b", text: "B. Increase in the general prices of goods and services", weight: 5, isCorrect: true },
      { id: "a1_c", text: "C. Increase in company profits", weight: 1 },
      { id: "a1_d", text: "D. Decrease in population", weight: 1 },
    ],
    scoringRules: "Objective General Awareness scoring.",
    explanation: "Inflation represents the broad increase in prices of goods and services, reducing purchasing power.",
    tags: ["Economy", "Inflation"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Remember", targetTrait: "Economic Awareness" },
  },
  {
    id: "a_gdp_02",
    stage: "awareness",
    domain: "Economic Awareness",
    subDomain: "Gross Domestic Product",
    difficulty: "Easy",
    type: "mcq",
    questionText: "GDP (Gross Domestic Product) is primarily used to measure:",
    estimatedTimeSeconds: 20,
    marks: 1.0,
    options: [
      { id: "a2_a", text: "A. Population growth", weight: 1 },
      { id: "a2_b", text: "B. A country's economic output", weight: 5, isCorrect: true },
      { id: "a2_c", text: "C. Government debt", weight: 1 },
      { id: "a2_d", text: "D. Number of businesses", weight: 1 },
    ],
    scoringRules: "Objective General Awareness scoring.",
    explanation: "GDP measures the total monetary value of finished goods and services produced within a country.",
    tags: ["GDP", "Macroeconomics"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Understand", targetTrait: "Economic Awareness" },
  },
  {
    id: "a_bank_03",
    stage: "awareness",
    domain: "Banking Knowledge",
    subDomain: "Central Banking & Monetary Policy",
    difficulty: "Medium",
    type: "mcq",
    questionText: "Which institution is primarily responsible for setting monetary policy in India?",
    estimatedTimeSeconds: 20,
    marks: 1.0,
    options: [
      { id: "a3_a", text: "A. Ministry of Finance", weight: 1 },
      { id: "a3_b", text: "B. Reserve Bank of India (RBI)", weight: 5, isCorrect: true },
      { id: "a3_c", text: "C. SEBI", weight: 1 },
      { id: "a3_d", text: "D. NITI Aayog", weight: 1 },
    ],
    scoringRules: "Objective General Awareness scoring.",
    explanation: "The Reserve Bank of India (RBI) manages interest rates, money supply, and inflation control.",
    tags: ["Banking", "RBI", "MonetaryPolicy"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Remember", targetTrait: "Banking Knowledge" },
  },
  {
    id: "a_pf_04",
    stage: "awareness",
    domain: "Financial Awareness",
    subDomain: "Equity & Capital Ownership",
    difficulty: "Easy",
    type: "mcq",
    questionText: "Which investment generally offers ownership in a company?",
    estimatedTimeSeconds: 20,
    marks: 1.0,
    options: [
      { id: "a4_a", text: "A. Fixed Deposit", weight: 1 },
      { id: "a4_b", text: "B. Savings Account", weight: 1 },
      { id: "a4_c", text: "C. Equity Shares (Stocks)", weight: 5, isCorrect: true },
      { id: "a4_d", text: "D. Gold Loan", weight: 1 },
    ],
    scoringRules: "Objective General Awareness scoring.",
    explanation: "Purchasing equity shares represents buying fractional ownership in a corporation.",
    tags: ["Stocks", "Investing", "Equity"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Understand", targetTrait: "Financial Awareness" },
  },
  {
    id: "a_tax_05",
    stage: "awareness",
    domain: "Civic Awareness",
    subDomain: "Public Fiscal Policy",
    difficulty: "Easy",
    type: "mcq",
    questionText: "Why do governments collect taxes?",
    estimatedTimeSeconds: 20,
    marks: 1.0,
    options: [
      { id: "a5_a", text: "A. To reduce population", weight: 1 },
      { id: "a5_b", text: "B. To fund public services and infrastructure", weight: 5, isCorrect: true },
      { id: "a5_c", text: "C. To increase inflation", weight: 1 },
      { id: "a5_d", text: "D. To regulate weather", weight: 1 },
    ],
    scoringRules: "Objective General Awareness scoring.",
    explanation: "Taxes fund essential public infrastructure, healthcare, defense, and social programs.",
    tags: ["Taxes", "Civics", "FiscalPolicy"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Understand", targetTrait: "Civic Awareness" },
  },
  {
    id: "a_ai_06",
    stage: "awareness",
    domain: "AI Literacy",
    subDomain: "AI Fundamentals",
    difficulty: "Easy",
    type: "mcq",
    questionText: "Which statement best describes Artificial Intelligence (AI)?",
    estimatedTimeSeconds: 20,
    marks: 1.0,
    options: [
      { id: "a6_a", text: "A. A programming language", weight: 1 },
      { id: "a6_b", text: "B. A system that performs tasks requiring human intelligence", weight: 5, isCorrect: true },
      { id: "a6_c", text: "C. A computer operating system", weight: 1 },
      { id: "a6_d", text: "D. A type of database", weight: 1 },
    ],
    scoringRules: "Objective General Awareness scoring.",
    explanation: "AI refers to computer systems engineered to simulate human cognitive functions like learning and reasoning.",
    tags: ["AI", "Technology"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Understand", targetTrait: "AI Literacy" },
  },
  {
    id: "a_sec_07",
    stage: "awareness",
    domain: "Cybersecurity Awareness",
    subDomain: "Password Complexity & Security",
    difficulty: "Medium",
    type: "mcq",
    questionText: "Which of the following is considered the strongest password?",
    estimatedTimeSeconds: 20,
    marks: 1.0,
    options: [
      { id: "a7_a", text: "A. 12345678", weight: 1 },
      { id: "a7_b", text: "B. password123", weight: 1 },
      { id: "a7_c", text: "C. John2004", weight: 1 },
      { id: "a7_d", text: "D. T9@vL#82mQ!x", weight: 5, isCorrect: true },
    ],
    scoringRules: "Objective General Awareness scoring.",
    explanation: "Option D includes uppercase letters, lowercase letters, numbers, and special symbols preventing brute-force attacks.",
    tags: ["Cybersecurity", "PasswordSecurity"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Cybersecurity Awareness" },
  },
  {
    id: "a_net_08",
    stage: "awareness",
    domain: "Technology Awareness",
    subDomain: "Web Encryption & HTTPS",
    difficulty: "Easy",
    type: "mcq",
    questionText: "What does HTTPS primarily provide compared to HTTP?",
    estimatedTimeSeconds: 20,
    marks: 1.0,
    options: [
      { id: "a8_a", text: "A. Faster internet speed", weight: 1 },
      { id: "a8_b", text: "B. Secure encrypted communication", weight: 5, isCorrect: true },
      { id: "a8_c", text: "C. Larger storage", weight: 1 },
      { id: "a8_d", text: "D. Better search rankings", weight: 1 },
    ],
    scoringRules: "Objective General Awareness scoring.",
    explanation: "HTTPS uses SSL/TLS encryption to protect data sent between your browser and the server.",
    tags: ["HTTPS", "WebSecurity"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Understand", targetTrait: "Technology Awareness" },
  },
  {
    id: "a_biz_09",
    stage: "awareness",
    domain: "Business & Entrepreneurship Awareness",
    subDomain: "Startup Value Proposition",
    difficulty: "Easy",
    type: "mcq",
    questionText: "What is the primary objective of a startup?",
    estimatedTimeSeconds: 20,
    marks: 1.0,
    options: [
      { id: "a9_a", text: "A. To avoid innovation", weight: 1 },
      { id: "a9_b", text: "B. To solve a problem with a scalable business model", weight: 5, isCorrect: true },
      { id: "a9_c", text: "C. To eliminate competition", weight: 1 },
      { id: "a9_d", text: "D. To reduce taxes", weight: 1 },
    ],
    scoringRules: "Objective General Awareness scoring.",
    explanation: "Startups focus on validating and scaling a solution to a meaningful problem.",
    tags: ["Startups", "BusinessModel"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Understand", targetTrait: "Business & Entrepreneurship Awareness" },
  },
  {
    id: "a_ent_10",
    stage: "awareness",
    domain: "Business & Entrepreneurship Awareness",
    subDomain: "Entrepreneurial Mindset",
    difficulty: "Easy",
    type: "mcq",
    questionText: "Which quality is most important for an entrepreneur?",
    estimatedTimeSeconds: 20,
    marks: 1.0,
    options: [
      { id: "a10_a", text: "A. Avoiding all risks", weight: 1 },
      { id: "a10_b", text: "B. Willingness to identify opportunities and solve problems", weight: 5, isCorrect: true },
      { id: "a10_c", text: "C. Memorizing textbooks", weight: 1 },
      { id: "a10_d", text: "D. Never changing plans", weight: 1 },
    ],
    scoringRules: "Objective General Awareness scoring.",
    explanation: "Opportunity identification and problem solving drive entrepreneurial success.",
    tags: ["Entrepreneurship", "Mindset"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Business & Entrepreneurship Awareness" },
  },
  {
    id: "a_geo_11",
    stage: "awareness",
    domain: "General World Awareness",
    subDomain: "Physical Geography",
    difficulty: "Easy",
    type: "mcq",
    questionText: "Which is the largest ocean on Earth?",
    estimatedTimeSeconds: 20,
    marks: 1.0,
    options: [
      { id: "a11_a", text: "A. Atlantic Ocean", weight: 1 },
      { id: "a11_b", text: "B. Indian Ocean", weight: 1 },
      { id: "a11_c", text: "C. Pacific Ocean", weight: 5, isCorrect: true },
      { id: "a11_d", text: "D. Arctic Ocean", weight: 1 },
    ],
    scoringRules: "Objective General Awareness scoring.",
    explanation: "The Pacific Ocean is the largest and deepest ocean basin on Earth.",
    tags: ["Geography", "WorldAwareness"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Remember", targetTrait: "General World Awareness" },
  },
  {
    id: "a_env_12",
    stage: "awareness",
    domain: "Environmental Awareness",
    subDomain: "Plastic Waste Reduction",
    difficulty: "Easy",
    type: "mcq",
    questionText: "Which activity contributes most to reducing plastic pollution?",
    estimatedTimeSeconds: 20,
    marks: 1.0,
    options: [
      { id: "a12_a", text: "A. Burning plastic waste", weight: 1 },
      { id: "a12_b", text: "B. Recycling and reducing single-use plastics", weight: 5, isCorrect: true },
      { id: "a12_c", text: "C. Throwing plastic into rivers", weight: 1 },
      { id: "a12_d", text: "D. Burying plastic underground", weight: 1 },
    ],
    scoringRules: "Objective General Awareness scoring.",
    explanation: "Reducing consumption of single-use plastics and recycling prevents marine and terrestrial contamination.",
    tags: ["Environment", "Recycling"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Environmental Awareness" },
  },
  {
    id: "a_civ_13",
    stage: "awareness",
    domain: "Civic Awareness",
    subDomain: "Constitutional Governance",
    difficulty: "Easy",
    type: "mcq",
    questionText: "In a democratic country, the Constitution primarily serves to:",
    estimatedTimeSeconds: 20,
    marks: 1.0,
    options: [
      { id: "a13_a", text: "A. Control businesses", weight: 1 },
      { id: "a13_b", text: "B. Define the framework of government and protect citizens' rights", weight: 5, isCorrect: true },
      { id: "a13_c", text: "C. Increase taxes", weight: 1 },
      { id: "a13_d", text: "D. Regulate weather", weight: 1 },
    ],
    scoringRules: "Objective General Awareness scoring.",
    explanation: "The Constitution establishes the fundamental legal framework and guarantees citizen rights.",
    tags: ["Constitution", "Civics"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Understand", targetTrait: "Civic Awareness" },
  },
  {
    id: "a_sci_14",
    stage: "awareness",
    domain: "Scientific Awareness",
    subDomain: "Plant Photosynthesis",
    difficulty: "Easy",
    type: "mcq",
    questionText: "Which gas do plants primarily absorb during photosynthesis?",
    estimatedTimeSeconds: 20,
    marks: 1.0,
    options: [
      { id: "a14_a", text: "A. Oxygen", weight: 1 },
      { id: "a14_b", text: "B. Carbon Dioxide", weight: 5, isCorrect: true },
      { id: "a14_c", text: "C. Nitrogen", weight: 1 },
      { id: "a14_d", text: "D. Hydrogen", weight: 1 },
    ],
    scoringRules: "Objective General Awareness scoring.",
    explanation: "Plants absorb Carbon Dioxide and water to produce glucose and oxygen using sunlight.",
    tags: ["Science", "Photosynthesis"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Remember", targetTrait: "Scientific Awareness" },
  },
  {
    id: "a_ca_15",
    stage: "awareness",
    domain: "General World Awareness",
    subDomain: "Current Affairs Value",
    difficulty: "Easy",
    type: "mcq",
    questionText: "Why is it important to stay informed about current events?",
    estimatedTimeSeconds: 20,
    marks: 1.0,
    options: [
      { id: "a15_a", text: "A. To spend more time on social media", weight: 1 },
      { id: "a15_b", text: "B. To make informed personal, financial, and civic decisions", weight: 5, isCorrect: true },
      { id: "a15_c", text: "C. To memorize news headlines", weight: 1 },
      { id: "a15_d", text: "D. To increase internet speed", weight: 1 },
    ],
    scoringRules: "Objective General Awareness scoring.",
    explanation: "Staying updated enables sound personal risk management, strategic career decisions, and responsible citizenship.",
    tags: ["CurrentAffairs", "WorldAwareness"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "General World Awareness" },
  },
];

// ================= STAGE 5: APTITUDE ASSESSMENT (10 Questions → 10 Marks) =================
export const APTITUDE_QUESTION_BANK: QuestionItem[] = [
  {
    id: "apt_easy_01",
    stage: "aptitude",
    domain: "Numerical Ability",
    subDomain: "Basic Multiplication",
    difficulty: "Easy",
    type: "mcq",
    questionText: "If 15 × 8 = ?",
    estimatedTimeSeconds: 15,
    marks: 1.0,
    options: [
      { id: "apt1_a", text: "A. 100", weight: 1 },
      { id: "apt1_b", text: "B. 110", weight: 1 },
      { id: "apt1_c", text: "C. 120", weight: 5, isCorrect: true },
      { id: "apt1_d", text: "D. 130", weight: 1 },
    ],
    scoringRules: "Numerical calculation scoring.",
    explanation: "15 × 8 = 120.",
    tags: ["Aptitude", "Numerical"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Remember", targetTrait: "Numerical Ability" },
  },
  {
    id: "apt_easy_02",
    stage: "aptitude",
    domain: "Logical Reasoning",
    subDomain: "Deductive Logic",
    difficulty: "Easy",
    type: "mcq",
    questionText: "If all roses are flowers and some flowers fade quickly, which statement is definitely true?",
    estimatedTimeSeconds: 20,
    marks: 1.0,
    options: [
      { id: "apt2_a", text: "A. All flowers are roses.", weight: 1 },
      { id: "apt2_b", text: "B. Some roses fade quickly.", weight: 1 },
      { id: "apt2_c", text: "C. Roses are flowers.", weight: 5, isCorrect: true },
      { id: "apt2_d", text: "D. No flowers fade quickly.", weight: 1 },
    ],
    scoringRules: "Deductive logic statement verification.",
    explanation: "Since all roses are flowers, it is definitely true that roses are flowers.",
    tags: ["Aptitude", "Logic"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Understand", targetTrait: "Logical Reasoning" },
  },
  {
    id: "apt_easy_03",
    stage: "aptitude",
    domain: "Pattern Recognition",
    subDomain: "Doubling Series",
    difficulty: "Easy",
    type: "mcq",
    questionText: "Find the next number in the series: 2, 4, 8, 16, ?",
    estimatedTimeSeconds: 15,
    marks: 1.0,
    options: [
      { id: "apt3_a", text: "A. 24", weight: 1 },
      { id: "apt3_b", text: "B. 30", weight: 1 },
      { id: "apt3_c", text: "C. 32", weight: 5, isCorrect: true },
      { id: "apt3_d", text: "D. 36", weight: 1 },
    ],
    scoringRules: "Geometric doubling pattern.",
    explanation: "Each term is multiplied by 2: 16 × 2 = 32.",
    tags: ["Aptitude", "Patterns"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Pattern Recognition" },
  },
  {
    id: "apt_med_04",
    stage: "aptitude",
    domain: "Numerical Ability",
    subDomain: "Discount Percentage",
    difficulty: "Medium",
    type: "mcq",
    questionText: "A shop gives a 20% discount on a ₹2,000 item. What is the final price?",
    estimatedTimeSeconds: 25,
    marks: 1.0,
    options: [
      { id: "apt4_a", text: "A. ₹1,400", weight: 1 },
      { id: "apt4_b", text: "B. ₹1,500", weight: 1 },
      { id: "apt4_c", text: "C. ₹1,600", weight: 5, isCorrect: true },
      { id: "apt4_d", text: "D. ₹1,800", weight: 1 },
    ],
    scoringRules: "Percentage discount calculation.",
    explanation: "Discount = 20% of 2000 = ₹400. Final Price = 2000 - 400 = ₹1,600.",
    tags: ["Aptitude", "DiscountMath"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Numerical Ability" },
  },
  {
    id: "apt_med_05",
    stage: "aptitude",
    domain: "Logical Reasoning",
    subDomain: "Odd One Out",
    difficulty: "Medium",
    type: "mcq",
    questionText: "Which word does NOT belong with the others?",
    estimatedTimeSeconds: 15,
    marks: 1.0,
    options: [
      { id: "apt5_a", text: "A. Apple", weight: 1 },
      { id: "apt5_b", text: "B. Mango", weight: 1 },
      { id: "apt5_c", text: "C. Banana", weight: 1 },
      { id: "apt5_d", text: "D. Carrot", weight: 5, isCorrect: true },
    ],
    scoringRules: "Category classification.",
    explanation: "Carrot is a vegetable while Apple, Mango, and Banana are fruits.",
    tags: ["Aptitude", "Classification"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Understand", targetTrait: "Logical Reasoning" },
  },
  {
    id: "apt_med_06",
    stage: "aptitude",
    domain: "Data Interpretation",
    subDomain: "Average Calculation",
    difficulty: "Medium",
    type: "mcq",
    questionText: "A student scored Math = 80, Science = 90, English = 70, History = 60. What is the average score?",
    estimatedTimeSeconds: 25,
    marks: 1.0,
    options: [
      { id: "apt6_a", text: "A. 70", weight: 1 },
      { id: "apt6_b", text: "B. 72.5", weight: 1 },
      { id: "apt6_c", text: "C. 75", weight: 5, isCorrect: true },
      { id: "apt6_d", text: "D. 80", weight: 1 },
    ],
    scoringRules: "Arithmetic mean calculation.",
    explanation: "Sum = 80 + 90 + 70 + 60 = 300. Average = 300 / 4 = 75.",
    tags: ["Aptitude", "DataInterpretation"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Data Interpretation" },
  },
  {
    id: "apt_med_07",
    stage: "aptitude",
    domain: "Pattern Recognition",
    subDomain: "Alphabet Incremental Series",
    difficulty: "Medium",
    type: "mcq",
    questionText: "Find the next letter in the pattern: A, C, F, J, O, ?",
    estimatedTimeSeconds: 25,
    marks: 1.0,
    options: [
      { id: "apt7_a", text: "A. S", weight: 1 },
      { id: "apt7_b", text: "B. T", weight: 1 },
      { id: "apt7_c", text: "C. U", weight: 5, isCorrect: true },
      { id: "apt7_d", text: "D. V", weight: 1 },
    ],
    scoringRules: "Letter step pattern: +2, +3, +4, +5, +6.",
    explanation: "O (15th letter) + 6 = 21st letter = U.",
    tags: ["Aptitude", "AlphabetSeries"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Analyze", targetTrait: "Pattern Recognition" },
  },
  {
    id: "apt_med_08",
    stage: "aptitude",
    domain: "Analytical Thinking",
    subDomain: "Linear Row Arrangement",
    difficulty: "Medium",
    type: "mcq",
    questionText: "Five people stand in a row. Rahul is to the left of Ankit. Ankit is to the left of Priya. Who must be in the middle?",
    estimatedTimeSeconds: 25,
    marks: 1.0,
    options: [
      { id: "apt8_a", text: "A. Rahul", weight: 1 },
      { id: "apt8_b", text: "B. Priya", weight: 1 },
      { id: "apt8_c", text: "C. Ankit", weight: 5, isCorrect: true },
      { id: "apt8_d", text: "D. Cannot be determined", weight: 1 },
    ],
    scoringRules: "Linear spatial arrangement logic.",
    explanation: "Order: [Person 1, Rahul, Ankit, Priya, Person 5]. Ankit is in position 3 (the middle).",
    tags: ["Aptitude", "Arrangements"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Analyze", targetTrait: "Analytical Thinking" },
  },
  {
    id: "apt_hard_09",
    stage: "aptitude",
    domain: "Numerical Ability",
    subDomain: "Speed-Distance-Time Calculation",
    difficulty: "Hard",
    type: "mcq",
    questionText: "A train travels 240 km in 3 hours. If it continues at the same speed, how far will it travel in 5.5 hours?",
    estimatedTimeSeconds: 30,
    marks: 1.0,
    options: [
      { id: "apt9_a", text: "A. 400 km", weight: 1 },
      { id: "apt9_b", text: "B. 420 km", weight: 1 },
      { id: "apt9_c", text: "C. 440 km", weight: 5, isCorrect: true },
      { id: "apt9_d", text: "D. 460 km", weight: 1 },
    ],
    scoringRules: "Speed-distance math calculation.",
    explanation: "Speed = 240 / 3 = 80 km/h. Distance = 80 × 5.5 = 440 km.",
    tags: ["Aptitude", "SpeedDistance"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Analytical Thinking" },
  },
  {
    id: "apt_hard_10",
    stage: "aptitude",
    domain: "Logical Reasoning",
    subDomain: "Clock Hand Geometry",
    difficulty: "Hard",
    type: "mcq",
    questionText: "A clock shows 3:00 PM. What is the angle between the hour hand and the minute hand?",
    estimatedTimeSeconds: 25,
    marks: 1.0,
    options: [
      { id: "apt10_a", text: "A. 60°", weight: 1 },
      { id: "apt10_b", text: "B. 75°", weight: 1 },
      { id: "apt10_c", text: "C. 90°", weight: 5, isCorrect: true },
      { id: "apt10_d", text: "D. 120°", weight: 1 },
    ],
    scoringRules: "Geometric angle measurement.",
    explanation: "At 3:00, the hour hand points to 3 and minute hand to 12, forming a right angle (90°).",
    tags: ["Aptitude", "Geometry", "ClockAngle"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Analyze", targetTrait: "Logical Reasoning" },
  },
];

// ================= STAGE 6: COMMUNICATION & LEARNING AGILITY ASSESSMENT (15 Questions → 15 Marks) =================
export const COMMUNICATION_QUESTION_BANK: QuestionItem[] = [
  // --- Section 1: Reading Comprehension (3 Qs → 3 Marks) ---
  {
    id: "com_rc_01",
    stage: "communication",
    domain: "Reading Comprehension",
    subDomain: "Fact Retrieval",
    difficulty: "Easy",
    type: "mcq",
    scenarioText: '"Artificial Intelligence is transforming industries by automating repetitive tasks and assisting humans in making better decisions. However, critical thinking and creativity remain essential human skills."',
    questionText: "According to the passage, AI mainly helps by:",
    estimatedTimeSeconds: 20,
    marks: 1.0,
    options: [
      { id: "com1_a", text: "A. Replacing all human jobs", weight: 1 },
      { id: "com1_b", text: "B. Automating repetitive tasks and assisting decision-making", weight: 5, isCorrect: true },
      { id: "com1_c", text: "C. Eliminating creativity", weight: 1 },
      { id: "com1_d", text: "D. Reducing education", weight: 1 },
    ],
    scoringRules: "Reading comprehension factual analysis.",
    explanation: "The passage explicitly states AI helps by automating repetitive tasks and assisting humans in making better decisions.",
    tags: ["ReadingComprehension", "FactRetrieval"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Understand", targetTrait: "Reading Comprehension" },
  },
  {
    id: "com_rc_02",
    stage: "communication",
    domain: "Reading Comprehension",
    subDomain: "Detail Extraction",
    difficulty: "Easy",
    type: "mcq",
    scenarioText: '"Artificial Intelligence is transforming industries by automating repetitive tasks and assisting humans in making better decisions. However, critical thinking and creativity remain essential human skills."',
    questionText: "Which skill does the passage say will remain essential?",
    estimatedTimeSeconds: 20,
    marks: 1.0,
    options: [
      { id: "com2_a", text: "A. Memorization", weight: 1 },
      { id: "com2_b", text: "B. Typing", weight: 1 },
      { id: "com2_c", text: "C. Critical Thinking and Creativity", weight: 5, isCorrect: true },
      { id: "com2_d", text: "D. Fast Reading", weight: 1 },
    ],
    scoringRules: "Reading comprehension detail extraction.",
    explanation: "The final sentence states that critical thinking and creativity remain essential human skills.",
    tags: ["ReadingComprehension", "DetailExtraction"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Understand", targetTrait: "Reading Comprehension" },
  },
  {
    id: "com_rc_03",
    stage: "communication",
    domain: "Reading Comprehension",
    subDomain: "Main Idea Synthesis",
    difficulty: "Medium",
    type: "mcq",
    scenarioText: '"Artificial Intelligence is transforming industries by automating repetitive tasks and assisting humans in making better decisions. However, critical thinking and creativity remain essential human skills."',
    questionText: "The main idea of the passage is:",
    estimatedTimeSeconds: 20,
    marks: 1.0,
    options: [
      { id: "com3_a", text: "A. AI makes humans unnecessary", weight: 1 },
      { id: "com3_b", text: "B. AI and human skills complement each other", weight: 5, isCorrect: true },
      { id: "com3_c", text: "C. AI is dangerous", weight: 1 },
      { id: "com3_d", text: "D. Creativity is not important", weight: 1 },
    ],
    scoringRules: "Main idea passage synthesis.",
    explanation: "The text emphasizes that AI automates tasks while human critical thinking remains essential, showing complementary value.",
    tags: ["ReadingComprehension", "MainIdea"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Analyze", targetTrait: "Reading Comprehension" },
  },

  // --- Section 2: Grammar & Vocabulary (3 Qs → 3 Marks) ---
  {
    id: "com_gv_04",
    stage: "communication",
    domain: "Grammar & Vocabulary",
    subDomain: "Subject-Verb Agreement",
    difficulty: "Easy",
    type: "mcq",
    questionText: "Choose the correct sentence.",
    estimatedTimeSeconds: 15,
    marks: 1.0,
    options: [
      { id: "com4_a", text: "A. She don't like coffee.", weight: 1 },
      { id: "com4_b", text: "B. She doesn't likes coffee.", weight: 1 },
      { id: "com4_c", text: "C. She doesn't like coffee.", weight: 5, isCorrect: true },
      { id: "com4_d", text: "D. She not like coffee.", weight: 1 },
    ],
    scoringRules: "Grammar syntax checking.",
    explanation: "Third-person singular negative present simple uses 'doesn't' + base verb 'like'.",
    tags: ["Grammar", "Syntax"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Grammar & Vocabulary" },
  },
  {
    id: "com_gv_05",
    stage: "communication",
    domain: "Grammar & Vocabulary",
    subDomain: "Synonym Vocabulary",
    difficulty: "Easy",
    type: "mcq",
    questionText: "Choose the correct synonym for 'Diligent'.",
    estimatedTimeSeconds: 15,
    marks: 1.0,
    options: [
      { id: "com5_a", text: "A. Lazy", weight: 1 },
      { id: "com5_b", text: "B. Careful and hardworking", weight: 5, isCorrect: true },
      { id: "com5_c", text: "C. Angry", weight: 1 },
      { id: "com5_d", text: "D. Confused", weight: 1 },
    ],
    scoringRules: "Vocabulary synonym recognition.",
    explanation: "Diligent means showing care and conscientiousness in one's work or duties (Careful and hardworking).",
    tags: ["Vocabulary", "Synonym"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Remember", targetTrait: "Grammar & Vocabulary" },
  },
  {
    id: "com_gv_06",
    stage: "communication",
    domain: "Grammar & Vocabulary",
    subDomain: "Tense Structure",
    difficulty: "Easy",
    type: "mcq",
    questionText: "Choose the correct sentence.",
    estimatedTimeSeconds: 15,
    marks: 1.0,
    options: [
      { id: "com6_a", text: "A. He have completed the project.", weight: 1 },
      { id: "com6_b", text: "B. He has completed the project.", weight: 5, isCorrect: true },
      { id: "com6_c", text: "C. He completing the project.", weight: 1 },
      { id: "com6_d", text: "D. He completed has the project.", weight: 1 },
    ],
    scoringRules: "Present perfect tense grammar check.",
    explanation: "Third-person singular 'He' takes auxiliary 'has' in present perfect tense.",
    tags: ["Grammar", "Tenses"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Grammar & Vocabulary" },
  },

  // --- Section 3: Professional Writing (2 Qs → 2 Marks) ---
  {
    id: "com_pw_07",
    stage: "communication",
    domain: "Professional Writing",
    subDomain: "Email Tone & Etiquette",
    difficulty: "Easy",
    type: "mcq",
    questionText: "Which email opening is the most professional?",
    estimatedTimeSeconds: 15,
    marks: 1.0,
    options: [
      { id: "com7_a", text: "A. Hey Buddy", weight: 1 },
      { id: "com7_b", text: "B. Dear Hiring Manager,", weight: 5, isCorrect: true },
      { id: "com7_c", text: "C. What's up?", weight: 1 },
      { id: "com7_d", text: "D. Hello Dude", weight: 1 },
    ],
    scoringRules: "Business writing tone evaluation.",
    explanation: "'Dear Hiring Manager,' provides a respectful, formal, and professional opening.",
    tags: ["ProfessionalWriting", "EmailEtiquette"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Professional Writing" },
  },
  {
    id: "com_pw_08",
    stage: "communication",
    domain: "Professional Writing",
    subDomain: "Status Update Clarity",
    difficulty: "Medium",
    type: "mcq",
    scenarioText: "Your manager asks for an urgent project update.",
    questionText: "Which response is most professional?",
    estimatedTimeSeconds: 20,
    marks: 1.0,
    options: [
      { id: "com8_a", text: "A. I don't know.", weight: 1 },
      { id: "com8_b", text: "B. I'll send it later.", weight: 1 },
      { id: "com8_c", text: "C. The project is 80% complete and will be submitted by tomorrow.", weight: 5, isCorrect: true },
      { id: "com8_d", text: "D. It's almost done.", weight: 1 },
    ],
    scoringRules: "Business communication specificity.",
    explanation: "Option C gives clear quantitative progress and an explicit commitment deadline.",
    tags: ["ProfessionalWriting", "StatusReporting"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Professional Writing" },
  },

  // --- Section 4: Communication Skills (2 Qs → 2 Marks) ---
  {
    id: "com_cs_09",
    stage: "communication",
    domain: "Business Communication",
    subDomain: "Active Listening",
    difficulty: "Easy",
    type: "mcq",
    questionText: "During a team discussion, the best communication practice is:",
    estimatedTimeSeconds: 15,
    marks: 1.0,
    options: [
      { id: "com9_a", text: "A. Interrupt others frequently.", weight: 1 },
      { id: "com9_b", text: "B. Listen actively before responding.", weight: 5, isCorrect: true },
      { id: "com9_c", text: "C. Speak louder than everyone else.", weight: 1 },
      { id: "com9_d", text: "D. Ignore different opinions.", weight: 1 },
    ],
    scoringRules: "Team collaboration best practices.",
    explanation: "Active listening ensures mutual understanding and effective team collaboration.",
    tags: ["CommunicationSkills", "ActiveListening"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Business Communication" },
  },
  {
    id: "com_cs_10",
    stage: "communication",
    domain: "Business Communication",
    subDomain: "Feedback Receptivity",
    difficulty: "Easy",
    type: "mcq",
    questionText: "When receiving constructive feedback, you should:",
    estimatedTimeSeconds: 15,
    marks: 1.0,
    options: [
      { id: "com10_a", text: "A. Become defensive.", weight: 1 },
      { id: "com10_b", text: "B. Ignore the feedback.", weight: 1 },
      { id: "com10_c", text: "C. Listen carefully and use it to improve.", weight: 5, isCorrect: true },
      { id: "com10_d", text: "D. Argue with the reviewer.", weight: 1 },
    ],
    scoringRules: "Constructive feedback handling.",
    explanation: "Listening carefully and converting feedback into improvement action builds professional capability.",
    tags: ["CommunicationSkills", "Feedback"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Business Communication" },
  },

  // --- Section 5: Learning Agility (5 Qs → 5 Marks) ---
  {
    id: "com_la_11",
    stage: "communication",
    domain: "Curiosity Index",
    subDomain: "Intellectual Curiosity",
    difficulty: "Easy",
    type: "mcq",
    questionText: "When you encounter a topic you don't understand, what do you usually do?",
    estimatedTimeSeconds: 15,
    marks: 1.0,
    options: [
      { id: "com11_a", text: "A. Ignore it.", weight: 1 },
      { id: "com11_b", text: "B. Wait for someone to explain it.", weight: 1 },
      { id: "com11_c", text: "C. Research it using reliable sources.", weight: 5, isCorrect: true },
      { id: "com11_d", text: "D. Assume it is unimportant.", weight: 1 },
    ],
    scoringRules: "Self-directed research habits.",
    explanation: "Proactively researching unfamiliar concepts demonstrates a strong Curiosity Index.",
    tags: ["LearningAgility", "Curiosity"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Curiosity Index" },
  },
  {
    id: "com_la_12",
    stage: "communication",
    domain: "Technology Adoption Score",
    subDomain: "Early Tech Adoption",
    difficulty: "Easy",
    type: "mcq",
    scenarioText: "A new software tool is introduced at work.",
    questionText: "What do you do?",
    estimatedTimeSeconds: 15,
    marks: 1.0,
    options: [
      { id: "com12_a", text: "A. Refuse to use it.", weight: 1 },
      { id: "com12_b", text: "B. Wait until everyone else learns it.", weight: 1 },
      { id: "com12_c", text: "C. Learn it as early as possible.", weight: 5, isCorrect: true },
      { id: "com12_d", text: "D. Continue using the old method forever.", weight: 1 },
    ],
    scoringRules: "Technology adoption willingness.",
    explanation: "Early adoption of modern tools maintains technical productivity and competitive advantage.",
    tags: ["LearningAgility", "TechnologyAdoption"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Technology Adoption Score" },
  },
  {
    id: "com_la_13",
    stage: "communication",
    domain: "Reading Habit Score",
    subDomain: "Continuous Reading Habits",
    difficulty: "Easy",
    type: "mcq",
    questionText: "How do you usually improve your knowledge?",
    estimatedTimeSeconds: 15,
    marks: 1.0,
    options: [
      { id: "com13_a", text: "A. I rarely read anything.", weight: 1 },
      { id: "com13_b", text: "B. I depend only on social media.", weight: 1 },
      { id: "com13_c", text: "C. I regularly read books, articles, or trusted educational resources.", weight: 5, isCorrect: true },
      { id: "com13_d", text: "D. I avoid learning outside school or work.", weight: 1 },
    ],
    scoringRules: "Reading habit frequency and quality.",
    explanation: "Consistently reading books and trusted resources compounds intellectual capital.",
    tags: ["LearningAgility", "ReadingHabits"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Remember", targetTrait: "Reading Habit Score" },
  },
  {
    id: "com_la_14",
    stage: "communication",
    domain: "Continuous Learning Score",
    subDomain: "Knowledge Application",
    difficulty: "Easy",
    type: "mcq",
    scenarioText: "You complete an online course.",
    questionText: "What is the next best step?",
    estimatedTimeSeconds: 15,
    marks: 1.0,
    options: [
      { id: "com14_a", text: "A. Forget everything.", weight: 1 },
      { id: "com14_b", text: "B. Apply the knowledge through practice or projects.", weight: 5, isCorrect: true },
      { id: "com14_c", text: "C. Never use the skill.", weight: 1 },
      { id: "com14_d", text: "D. Wait several years before practicing.", weight: 1 },
    ],
    scoringRules: "Learning retention through application.",
    explanation: "Applying new knowledge in practical projects solidifies learning and skill mastery.",
    tags: ["LearningAgility", "ContinuousLearning"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Apply", targetTrait: "Continuous Learning Score" },
  },
  {
    id: "com_la_15",
    stage: "communication",
    domain: "Skill Development Score",
    subDomain: "Lifelong Upskilling",
    difficulty: "Easy",
    type: "mcq",
    scenarioText: "Technology changes rapidly.",
    questionText: "Which approach is most beneficial?",
    estimatedTimeSeconds: 15,
    marks: 1.0,
    options: [
      { id: "com15_a", text: "A. Learn only once.", weight: 1 },
      { id: "com15_b", text: "B. Continuously update your skills throughout your career.", weight: 5, isCorrect: true },
      { id: "com15_c", text: "C. Avoid learning new technologies.", weight: 1 },
      { id: "com15_d", text: "D. Depend entirely on your employer.", weight: 1 },
    ],
    scoringRules: "Lifelong upskilling strategy.",
    explanation: "Continuous skill updates prevent skill obsolescence in rapidly changing technological landscapes.",
    tags: ["LearningAgility", "SkillDevelopment"],
    aiEvaluationMetadata: { cognitiveTaxonomy: "Evaluate", targetTrait: "Skill Development Score" },
  },
];

export const QUESTION_BANK: QuestionItem[] = [
  ...PERSONALITY_QUESTION_BANK,
  ...MINDSET_QUESTION_BANK,
  ...DECISION_QUESTION_BANK,
  ...AWARENESS_QUESTION_BANK,
  ...APTITUDE_QUESTION_BANK,
  ...COMMUNICATION_QUESTION_BANK,
];
